feel-engine-plugin/README.md
use the feel engine plgin with camunda-spring-boot-starter
=> add camunda-spring-boot-starter doc

feel-engine/src/main/scala/org/camunda/feel/parser/FeelParser.scala
Background: When I tried to run some small scripts (~10 lines) which involved heavy usage of contexts and functions, I noticed that parsing was awfully slow, it took up to 15 seconds to complete (while evaluation was pretty fast). Also, you seemed to have some trouble at Camunda with similar problems: https://blog.camunda.org/post/2016/08/dmn-performance-improvements/.
This commit eliminates some repeated parsing of common prefixes with optional suffix, like _instance of_ expressions where _expression7_ might already been parsed successfully, but would be thrown away if not followed by an _instance of_. The other changes cover similar cases. All tests still succeed, their execution time drops roughly from 10s to 2s on my machine (measured by one-time cold run, actual parsing benefit …
=> Improved parser performance for instance of, comparisons and filter expressions

feel-engine-plugin/README.md
As you configure everything with the pomin spring boot setups, mention the dependency to SPIN explicitly.
=> mention SPIN dependency

docs/feel-expression.md, feel-engine/src/main/scala/org/camunda/feel/interpreter/FeelInterpreter.scala, feel-engine/src/test/scala/org/camunda/feel/interpreter/InterpreterDateTimeExpressionTest.scala
=> feat(engine): divide duration by another duration

feel-engine/src/main/scala/org/camunda/feel/interpreter/FeelInterpreter.scala, feel-engine/src/main/scala/org/camunda/feel/interpreter/Val.scala, feel-engine/src/test/scala/org/camunda/feel/interpreter/InterpreterContextExpressionTest.scala, feel-engine/src/test/scala/org/camunda/feel/interpreter/InterpreterListExpressionTest.scala
=> fix(engine): propagte errors in list and context

examples/pom.xml, examples/src/test/scala/org/camunda/feel/example/BasicFeelEngineFactoryTest.scala, examples/src/test/scala/org/camunda/feel/example/DmnEvaluationTest.scala, examples/src/test/scala/org/camunda/feel/example/FunctionProviderTest.scala, examples/src/test/scala/org/camunda/feel/example/spec/SpecExampleTest.scala, feel-engine-factory/pom.xml, feel-engine-factory/src/test/scala/org/camunda/feel/integration/CamundaDmnFeelEngineIntegrationTest.scala, feel-engine-plugin/pom.xml, feel-engine/pom.xml, feel-engine/src/main/scala/org/camunda/feel/interpreter/BuiltinFunctions.scala, feel-engine/src/main/scala/org/camunda/feel/interpreter/DefaultValueMapper.scala, feel-engine/src/main/scala/org/camunda/feel/script/FeelExpressionScriptEngine.scala, feel-engine/src/main/scala/org/camunda/feel/spi/JavaValueMapper.scala, feel-engine/src/test/scala/org/camunda/feel/FeelEngineTest.scala, pom.xml
=> Migrate feel to scala 2.13

docs/feel-expression.md, docs/feel-unary-tests.md
* correct the boolean disjunction/conjunction logic for null values (expression section)
* describe when a unary-tests expression is true (unary-tests section)
References:
* DMN 1.2 specification table 45 page 128
* DMN 1.2 specification section 8.3.3 page 90
=> Update documentation (expression/unary-tests)

feel-engine/src/main/scala/org/camunda/feel/impl/JavaValueMapper.scala, feel-engine/src/test/scala/org/camunda/feel/impl/spi/JavaValueMapperTest.scala
* transform a number that is greater than Long.MaxValue into a Double instead of a Long
Closes #90
=> fix(engine): transform big numeric values

.ci.cambpm
* build with JDK 8 and 11
Closes #96
=> chore(ci): build also with jdk 11

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
=> [Backport 1.11] Variable names can contain a key-word

docs/develop/feel-built-in-functions.md, src/main/scala/org/camunda/feel/impl/builtin/TemporalBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinTemporalFunctionsTest.scala
* add the following built-in functions: 
* `week of year()`
* `month of year()`
* `day of week()`
* `day of year()`
closes #180
=> New temporal date-time builtin functions (DMN 1.3)

src/main/scala/org/camunda/feel/impl/builtin/NumericBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinNumberFunctionTest.scala
* Added a fix for the modulo function to be able to operate with negative numbers.
closes #152
=> fix: added fix for negative numbers using modulo

docs/develop/feel-expression.md, src/main/scala/org/camunda/feel/impl/builtin/TemporalBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinTemporalFunctionsTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/DateTimeDurationPropertiesTest.scala
Signed-off-by: Kasper Aaquist Johansen <kasperaaquist@gmail.com>
* added the weekday Builtin function to date and datetime. 
closes #160
=> feat: added weekday for date and datetime, issue #160

src/main/scala/org/camunda/feel/impl/builtin/NumericBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinNumberFunctionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
* Add check for instance of Any 
closes #157
=> Add instance of any feature

src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala
* Added a fix for the number function to accept null for grouping and decimal values. 
closes #153
=> Add fix number function

pom.xml
The Scala Library is shaded inside a new artifact with the classifier `scala-shaded`
closes #149
=> Publish new artifact which shades the Scala Library 

pom.xml
Backports PR #202 to 1.11
Related to CAM-12136, #149
=> [Backport] feat(engine): publish scala-shaded artifact

.github/workflows/publish-docs.yaml, docs/src/css/custom.css
Restore the icons in the header.
=> Docs: Restore header icons

docs/docusaurus.config.js
Add the API key to enable the search.
=> Docs: insert the API key for the search

docs/package-lock.json, docs/package.json
* dump `docusaurus` from `2.0.0-alpha.69` to `2.0.0-alpha.70`
=> chore(deps): dump docusaurus to 2.0.0-alpha.70

docs/docs/samples/context-samples.md, docs/docs/samples/list-samples.md, docs/docs/samples/samples.md, docs/docs/samples/temporal-samples.md, docs/sidebars.js
* add more temporal samples
* split samples into different pages
=> Docs: Add more temporal samples

docs/docs/samples/temporal-samples.md
* add new temporal sample to calculate the next weekday
=> docs(sample): new temporal sample

docs/docs/reference/builtin-functions/feel-built-in-functions-conversion.md, src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
* new built-in function `context()` to create a context dynamically
closes #168
=> Add new built-in function context()

pom.xml
=> [Backport 1.13] chore(project): generate third-party dependency list

docs/docs/samples/list-samples.md, docs/docs/samples/temporal-samples.md
=> (docs) Add more samples

pom.xml, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/test/scala/org/camunda/feel/impl/interpreter/DateTimeDurationPropertiesTest.scala
* the weekday property is available for date-time values without timezone
closes #319
=> Access weekday property of local date-time value

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinStringFunctionsTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterBooleanExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterContextExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterFunctionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterNumberExpressionTest.scala
* rewrite the whole parser (to get rid of some old parts) 
* simplify the parsers by improving the hierarchy of the expressions
* removed unused parsers
**Hints**
I recommend looking just at the new parser. The comparison of the changes is not so useful because the structure of the parser changed too much. 
closes #312
=> FEEL parser overhaul :wrench: 

src/test/scala/org/camunda/feel/impl/interpreter/InterpreterBooleanExpressionTest.scala
* add new test case to verify that a conjunction can contain a some/every expression
closes #362
=> Verify conjunction with some expression

src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
* add a new test case to verify a unary-tests expression with a disjunction of two intervals
closes #349
=> Verify unary-tests with disjunction

docs/docs/changelog/changelog.md
* update changelog for new version 1.15.0
=> docs: update changelog for 1.15.0

docs/docs/tutorial/tutorial-1.md, docs/docs/tutorial/tutorial.md, docs/docusaurus.config.js, docs/sidebars.js
* the tutorial is a hack day project that we're currently working on
* add a new entry to the top navigation
* add some pages to start with the tutorial
related to #427
=> [Hack days] Add an entry for the tutorial

docs/src/components/EnvelopeAddress.js
* Fix the editor of the tutorial 2.1
=> Fix the editor of the tutorial 2.1 

docs/docs/tutorial/tutorial-1-1.md, docs/docs/tutorial/tutorial-1-2.md, docs/docs/tutorial/tutorial-1-3.md, docs/docs/tutorial/tutorial-2-1.mdx, docs/docs/tutorial/tutorial-3-1.md, docs/docs/tutorial/tutorial-3.md, docs/docs/tutorial/tutorial-4-1.md, docs/docs/tutorial/tutorial-4.md, docs/sidebars.js
Adjustment of structure of tutorial
* 
closes #
=> Updates to structure tutorial

docs/docs/tutorial/tutorial-4-1.md
Minor text corrections
* 
closes #
=> Text corrections

docs/src/components/EnvelopeAddress.js, docs/src/components/LiveFeel.js
* Update feel tutorial to use https url
=> FEEL tutorial: use https

docs/src/components/LiveFeel.js
* Adds some form of syntax highlighting to the FEEL evaluation error message
* If possible displays the line and position where the error occurred
NA
=> Improve error messages in the playground and tutorial

docs/src/components/LiveFeel.js
* If the context is not a correct JSON object, then we display an error message.
* If possible it also shows the position where the error
occurred.
Summer hackdays
=> Handle context errors elegantly

docs/docs/tutorial/tutorial-3-1.mdx
* polish tutorial 3-1
* make the example a bit easier
closes #
=> docs: polish tutorial 3-1

docs/docs/tutorial/tutorial-1-1.mdx, docs/docs/tutorial/tutorial-1-2.mdx, docs/docs/tutorial/tutorial-1-3.mdx, docs/docs/tutorial/tutorial-2-1.mdx, docs/docs/tutorial/tutorial.mdx, docs/src/components/Envelope.js, docs/src/components/EnvelopeAddress.js
=> Polishing tutorial (2)

docs/docs/tutorial/tutorial-3-2.mdx, docs/sidebars.js
* add a new tutorial 3-2
closes #
=> docs: add a new tutorial 3-2

pom.xml
* dump plugin versions for avoid issues on building a release
=> deps: dump plugin versions

docs/docs/reference/builtin-functions/feel-built-in-functions-temporal.md, pom.xml, src/main/scala/org/camunda/feel/impl/builtin/TemporalBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinTemporalFunctionsTest.scala
Add a function that allows the user to get the last day of a month for a passed in Date.
* 
closes #526
=> feat: Add built-in function to get the last day of the month

docs/docs/reference/builtin-functions/feel-built-in-functions-conversion.md, src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala
Adds the ability to pass in a timezone to data and time to convert the date and time to the timezone specified.
* 
closes #508
=> feat: New built-in function to get a date-time in a given timezone

pom.xml, src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala, src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterDateTimeExpressionTest.scala
* Normalized DayTimeDuration
closes #466
=> fix: normalize days-time duration values

src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala
* use only Java 8 compatible code
=> fix: Java 8 compatible code 

docs/docs/reference/language-guide/feel-context-expressions.md, docs/docs/reference/language-guide/feel-data-types.md, docs/docs/reference/language-guide/feel-variables.md, docs/versioned_docs/version-1.14/reference/language-guide/feel-context-expressions.md, docs/versioned_docs/version-1.14/reference/language-guide/feel-data-types.md, docs/versioned_docs/version-1.14/reference/language-guide/feel-variables.md, docs/versioned_docs/version-1.15/reference/language-guide/feel-context-expressions.md, docs/versioned_docs/version-1.15/reference/language-guide/feel-data-types.md, docs/versioned_docs/version-1.15/reference/language-guide/feel-variables.md
* Updated documentation for for data type and context. 
closes #334
=> docs(language-guide): Update docs for names

docs/docs/reference/language-guide/feel-boolean-expressions.md, src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/main/scala/org/camunda/package.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/DateTimeDurationPropertiesTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterDateTimeExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
* backport of #534 
* backport of #538 
* backport of #535
=> Backport bug fixes 

docs/docusaurus.config.js, docs/src/pages/index.js
- fix links to the GitHub repo
- update the description on the main page
=> docs: update config and main page

docs/docs/reference/developer-guide/value-mapper-spi.md, docs/versioned_docs/version-1.14/reference/developer-guide/value-mapper-spi.md, docs/versioned_docs/version-1.15/reference/developer-guide/value-mapper-spi.md
Mention the JavaValueMapper in the developer documentation.
closes #562
=> docs: Mention the JavaValueMapper

docs/docs/changelog/changelog.md, docs/versioned_docs/version-1.15/changelog/changelog.md
Update the changelog for the new release 1.16.
related to #610
=> docs: update changelog for 1.16

src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala
* fix toString() of ValDayTimeDuration
* add test cases for negative day/time durations
closes #599 
closes #598
=> fix(builtin-function): fix string conversion of days-times-durations

docs/docs/playground/playground.mdx, docs/src/components/FeelPlaygroundVersion.js, docs/src/components/LiveFeel.js, docs/versioned_docs/version-1.16/playground/playground.mdx
- Use the new API for the playground
- Show the version of the FEEL engine used by the playground
=> docs: Use new playground API

docs/docs/playground/playground.mdx, docs/src/components/FeelPlaygroundVersion.js, docs/src/components/LiveFeel.js, docs/src/components/LiveFeelUnaryTests.js, docs/versioned_docs/version-1.16/playground/playground.mdx
- Add Unary-Tests option for the Playground
- Use HTTPS for the playground API
=> docs: Evaluate Unary-tests in Playground 

docs/docs/learn/challenge/chapter-6.mdx, docs/versioned_docs/version-1.16/learn/challenge/chapter-6.mdx
Rewrite the chapter 6 of the challenge
=> docs: Rewrite chapter 6 of the challenge

docs/src/components/FeelPlaygroundVersion.js, docs/src/components/LiveFeel.js, docs/src/components/LiveFeelUnaryTests.js
Use new playground DNS: `feel.upgradingdave.com`
=> docs: Use new playground DNS

docs/docs/playground/playground.mdx, docs/versioned_docs/version-1.16/playground/playground.mdx
Remote the construction note from Playground. The construction is finished. :building_construction:
=> docs: Remote construction note from Playground

.github/workflows/build-maven.yml
We need to run the build and tests for both Java versions to ensure the compatibility with other products.
Resources:
- https://github.com/actions/setup-java#install-multiple-jdks
- https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#testing-against-different-java-distributions
=> ci: Build on Java 11 and Java 8

.github/workflows/release.yml
Move release workflow to GitHub actions. 
Inspired by https://github.com/camunda/zeebe/blob/main/.github/workflows/release.yml
closes #611
=> ci: Add GitHub release workflow

.ci.cambpm, .github/workflows/build-maven.yml, pom.xml
* bump the release parent version to pick up the source code level changes
* test feel-scala with JDK 11 and 17
* In C7 we use 1.15.x feel-scala, therefore this PR.
https://github.com/camunda/camunda-bpm-platform/issues/3690
=> chore(project): update to Java 11 source code level

.ci.cambpm, .github/workflows/release.yml
* Clean up release workflow
* Attach dependency list as release artifact
* Remove Jenkins CI 
closes #611
=> ci: Clean up GitHub release workflow

pom.xml
* Update to latest available maven-install-plugin version to resolve failure on 1.16 release flow
Successful dry run:
https://github.com/camunda/feel-scala/actions/runs/6251447218
closes #
=> chore(deps): update maven-install-plugin to 3.1.1

docs/src/components/LiveFeel.js, docs/src/components/LiveFeelUnaryTests.js
Update the Playground to show evaluation warnings.
---
=> docs: Show evaluation warnings in playground

pom.xml
* Backports of:
* https://github.com/camunda/feel-scala/commit/eb79e7ef633965adf59d3fa2ffca4c996eb344c3
* https://github.com/camunda/feel-scala/commit/fa9067664ebf87a43e6e76473e035af03f354848
closes #
=> build: configure maven-gpg-plugin

src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala
Fix a regression in the `string()` function when it is invoked for string or null values. 
closes #747 
closes #748
=> fix: Regression in string() function for string and null values

src/main/scala/org/camunda/feel/impl/interpreter/EvalContext.scala, src/test/scala/org/camunda/feel/impl/EvaluationResultMatchers.scala, src/test/scala/org/camunda/feel/impl/FeelEngineTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterContextExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/MyCustomContext.scala
Backport of #786 to `1.16`.
relates to #765 #774
=> [Backport 1.16] fix: Variable resolution for custom context

docs/docs/reference/developer-guide/function-provider-spi.md
* the SpiServiceLoader is explicitly mentioned
no issue, just a slack ref: https://camunda.slack.com/archives/C01QYD808A3/p1703234484514159
closes #
=> Give a hint on how to configure the feel engine to use the SPI function provider

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterInterruptionTest.scala
Backport of #824 to `1.17`.
relates to #823
original author: @vicmosin
=> [Backport 1.17] feat: I can interrupt an expression evaluation

pom.xml
Released new patch version 1.17.6. :building_construction:
=> Release 1.17.6

pom.xml
Released new version `1.17.7` :building_construction:
=> [Release] 1.17.7

docs/docs/playground/playground.mdx, docs/package-lock.json, docs/package.json, docs/src/components/LiveFeel.js, docs/src/components/LiveFeelUnaryTests.js, docs/versioned_docs/version-1.16/playground/playground.mdx, docs/versioned_docs/version-1.17/playground/playground.mdx
* Extend the Playground to share the expression via URL
* Update to Docusaurus 2.4 to select tabs with a query parameter
closes camunda-community-hub/feel-scala-playground/issues/58
=> docs: Share expression from Playground

src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
Add a new function to check if a list is empty.
closes #805
=> feat: add function to check if a list is empty

docs/docs/changelog/changelog.md, docs/versioned_docs/version-1.16/changelog/changelog.md, docs/versioned_docs/version-1.17/changelog/changelog.md
* Update the Camunda 7 versions in the Changelog
=> docs: Update changelog Camunda 7 versions

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/main/scala/org/camunda/feel/impl/parser/FeelWhitespace.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
Backport of #914 to `1.17`.
relates to #840
=> [Backport 1.17] fix: Parse expression with NBSP character

pom.xml
Released a new version `1.17.8`.
=> [Release] 1.17.8

pom.xml
Released a new version `1.16.4`.
=> [Release] 1.16.4

src/main/scala/org/camunda/feel/impl/builtin/StringBuiltinFunctions.scala
Refactor: change the UUID generator from v1 to v7
closes #923
=> refactor: Change the UUID generator from v1 to v7

pom.xml
Released a new version `1.16.5`.
=> [Release] 1.16.5

pom.xml
Released a new version `1.17.9`.
=> [Release] 1.17.9

src/main/scala/org/camunda/feel/impl/builtin/BuiltinFunction.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
Backport of #959 to `1.18`.
relates to camunda/camunda#26054
=> [Backport 1.18] fix: A unary-test expression with ? returns true/false

src/main/scala/org/camunda/feel/impl/builtin/BuiltinFunction.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
Backport of #959 to `1.19`.
relates to camunda/camunda#26054
=> [Backport 1.19] fix: A unary-test expression with ? returns true/false

src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
Backport of #970 to `1.18`.
relates to #957
=> [Backport 1.18] fix: List functions handle invalid zero position

src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
Backport of #970 to `1.17`.
relates to #957
=> [Backport 1.17] fix: List functions handle invalid zero position

pom.xml
Released a new version `1.17.10`.
=> [Release] 1.17.10

pom.xml
Released a new version `1.18.2`.
=> [Release] 1.18.2

pom.xml
Released a new version `1.17.11`.
=> [Release] 1.17.11

pom.xml
Released a new version `1.18.3`.
=> [Release] 1.18.3

pom.xml
Released a new version `1.19.2`.
=> [Release] 1.19.2

pom.xml
Backport of #1003 to `1.19`.
relates to 
original author: @HeleneW-dot
=> [Backport 1.19] chore(fasterxml): add relocation for fasterxml shading

feel-repl.sc
Update feel-repl.sc to 1.19.3
closes #
=> Update feel-repl.sc to 1.19.3

pom.xml
Released a new version `1.19.3`.
=> [Release] 1.19.3
