feel-engine/src/main/scala/org/camunda/feel/interpreter/FeelInterpreter.scala, feel-engine/src/test/scala/org/camunda/feel/interpreter/InterpreterExpressionTest.scala
Associated to #40 - My initial attempt supports `ValDate - ValDate` and `ValDate - ValYearMonthDuration`. I cannot figure out how to implement `ValDate - ValDayTimeDuration` (which would be required to do something like `date("2012-12-25") - duration("1D")`.
I also am slightly confused as to why the date subtraction produces negatives where I would expect positive and vice-versa. `time("10:00:00") - time("09:00:00")` returns `PT1H`, whereas `date("2012-12-25") - date("2012-12-24")` returns `P-1D`.
=> support date subtract date and date subtract year month duration

docs/feel-expression.md, feel-engine/src/main/scala/org/camunda/feel/parser/FeelParser.scala, feel-engine/src/test/scala/org/camunda/feel/interpreter/InterpreterExpressionTest.scala, feel-engine/src/test/scala/org/camunda/feel/parser/ParseExpressionTest.scala, feel-engine/src/test/scala/org/camunda/feel/parser/ParseUnaryTest.scala
=> chore(engine): escape names with ` instead of '

examples/README.md, examples/pom.xml, examples/project/build.properties, examples/project/plugins.sbt, examples/src/main/java/org/camunda/feel/example/spi/CustomJavaFunctionProvider.java, examples/src/main/java/org/camunda/feel/example/spi/CustomJavaValueMapper.java, examples/src/main/scala/org/camunda/feel/example/spi/CustomScalaFunctionProvider.scala, examples/src/test/java/org/camunda/feel/example/FeelEngineJavaTest.java, examples/src/test/resources/META-INF/services/org.camunda.feel.impl.spi.CustomFunctionProvider, examples/src/test/resources/basic/literalExpression.dmn, examples/src/test/resources/basic/outputExpression.dmn, examples/src/test/resources/basic/simpleUnaryTest.dmn, examples/src/test/resources/function/outputEntryWithFunction.dmn, examples/src/test/resources/log4j2.xml, examples/src/test/resources/spec/SpecExample.dmn, examples/src/test/scala/org/camunda/feel/example/BasicFeelEngineFactoryTest.scala, examples/src/test/scala/org/camunda/feel/example/DmnEvaluationTest.scala, examples/src/test/scala/org/camunda/feel/example/FunctionProviderTest.scala, examples/src/test/scala/org/camunda/feel/example/spec/Context.scala, examples/src/test/scala/org/camunda/feel/example/spec/SpecExampleTest.scala
Restore the examples sub-project in `feel-scala`. 
Separate the `examples` module as a separate project inside the repository to avoid cyclic dependencies with the DMN Engine.
=> CAM-11259: add back the examples

feel-engine/src/main/scala/org/camunda/feel/impl/parser/Exp.scala, feel-engine/src/main/scala/org/camunda/feel/interpreter/impl/FeelInterpreter.scala, feel-engine/src/test/scala/org/camunda/feel/interpreter/impl/InterpreterListExpressionTest.scala
Access an item of a list by providing a variable as the index.
```js
["a","b","c"][index]
// if index = 2 then result is "b"
```
Closes #80
=> fix(engine): access list by variable

feel-engine/src/test/scala/org/camunda/feel/context/JavaCustomFunctionTest.scala, feel-engine/src/test/scala/org/camunda/feel/context/SimpleTestJavaFunctionProvider.java, feel-engine/src/test/scala/org/camunda/feel/impl/spi/CustomContextTest.scala, feel-engine/src/test/scala/org/camunda/feel/impl/spi/SimpleTestContext.scala, feel-engine/src/test/scala/org/camunda/feel/valuemapper/BuiltinValueMapperInputTest.scala, feel-engine/src/test/scala/org/camunda/feel/valuemapper/BultinValueMapperOutputTest.scala, feel-engine/src/test/scala/org/camunda/feel/valuemapper/SimpleTestPojo.java
Adds tests for the following scenarios:
* Register custom function providers using the `JavaFunctionProvider`
* Evaluate...
* expressions with context and result "left" & "right"
* unary-tests with context and result "left" & "right"
* Built-in value mappers tested in a blackbox manner
Closes #103
=> Increase test coverage

CONTRIBUTING.md
Describes what we consider API of this project and what changes must lead to a major release according to semantic versioning. Based on the discussion we had today.
@saig0, @tasso94: In this exceptional case, I think it would be good if one member of each team reviews that this captures everything as discussed.
Closes #95
=> chore(project): define API guarantees

feel-engine/src/main/scala/org/camunda/feel/impl/DefaultValueMapper.scala, feel-engine/src/test/scala/org/camunda/feel/valuemapper/BuiltinValueMapperInputTest.scala, feel-engine/src/test/scala/org/camunda/feel/valuemapper/BultinValueMapperOutputTest.scala
* the default value mapper reads values of type `short` as FEEL number
Closes #110
=> feat(engine): read short as FEEL number

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/interpreter/impl/InterpreterContextExpressionTest.scala, src/test/scala/org/camunda/feel/interpreter/impl/InterpreterListExpressionTest.scala, src/test/scala/org/camunda/feel/interpreter/impl/InterpreterUnaryTest.scala
* in an expression, a list/context value can be compared to another list/context value
* two contexts are equal if they have the same keys and every entry is equal
* two lists are equal if they have the same size and every item is equal
* ignore failures when comparing the entries/items (e.g. different types)
* in a unary-test, a list/context input value can be compared to a list/context value
closes #134
=> fix(engine): compare context and list values

pom.xml
* The Maven coordinates for the Scala FEEL Engine should remain org.camunda.feel:feel-engine
Closes #143
=> fix(project): restore correct maven coordinates

docs/develop/feel-built-in-functions.md, docs/develop/feel-expression.md, src/main/scala/org/camunda/feel/impl/interpreter/BuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinFunctionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
* comparing a non-existing variable with `null` returns `true`
* comparing a property with `null` returns `true` if the property is `null`, if it doesn't exist, or if its variable is `null` or doesn't exist 
* new built-in function `is defined()` that returns `true` if the given value is present (i.e. is not an error)
closes #150
=> Compare not existing variables with null

docs/develop/feel-built-in-functions.md, docs/develop/feel-expression.md, src/main/scala/org/camunda/feel/impl/interpreter/BuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinFunctionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
* backport #176 to `1.11.x` 
closes #150
=> [Backport 1.11] Compare not existing variables with null

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
* allow variable names that contain a key-word 
* remove some cuts `!` in the parser that stopped the back-tracking 
closes #147
=> Variable names can contain a key-word

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
* adjust the parser to allow variable names with a date-time keyword 
closes #184
=> Allow variable names with date-time keywords

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
=> [Backport 1.12] Allow variable names with date-time keywords

src/main/scala/org/camunda/feel/FeelEngine.scala
* use the provided clock when creating the engine with the builder
closes #188
=> Use the clock when creating the engine with the builder 

src/main/scala/org/camunda/feel/FeelEngine.scala
=> [Backport 1.12] Use the clock when creating the engine with the builder

src/main/scala/org/camunda/feel/impl/builtin/NumericBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinNumberFunctionTest.scala
Signed-off-by: Kasper Aaquist Johansen <kasperaaquist@gmail.com>
* Made oddFunction return `true` when evaluating negative numbers.  
closes #151
=> fix: fixed oddFunction to eval negative numbers

src/main/scala/org/camunda/feel/impl/builtin/NumericBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinNumberFunctionTest.scala
* The `abs()` can now be invoked either with a named parameter `n` or `number`
closes #164
=> fix: fixed abs() function to be invoked with named parameter "n"

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
=> [Backport 1.11] Allow variable names with date-time keywords

src/main/scala/org/camunda/feel/impl/interpreter/ObjectContext.scala, src/test/java/org/camunda/feel/valuemapper/SimpleBooleanTestPojo.java, src/test/scala/org/camunda/feel/api/valuemapper/BuiltinValueMapperInputTest.scala
In `ObjectContext`, respect boolean accessors prepended with "is".
related to CAM-12577, closes #212
=> fix(ObjectContext): respect boolean accessors prepended with "is"

src/main/scala/org/camunda/feel/impl/interpreter/ObjectContext.scala, src/test/java/org/camunda/feel/valuemapper/SimpleBooleanTestPojo.java, src/test/scala/org/camunda/feel/api/valuemapper/BuiltinValueMapperInputTest.scala
=> [Backport 1.11] Object context should respect boolean accessors prepended with "is"

src/main/scala/org/camunda/feel/impl/interpreter/ObjectContext.scala, src/test/java/org/camunda/feel/valuemapper/SimpleBooleanTestPojo.java, src/test/scala/org/camunda/feel/api/valuemapper/BuiltinValueMapperInputTest.scala
=> [Backport 1.12] Object context should respect boolean accessors prepended with "is"

feel-repl.sc
* add a new function for the REPL to provide variables as a JSON string instead of a map
* use [uPickle](http://www.lihaoyi.com/upickle/#uJson) to deserialize the JSON string because it is already bundled in the Ammonite REPL (i.e. no additional dependency to download) 
closes #223
=> REPL: provide variables as JSON

README.md, pom.xml
We are currently renaming Camunda BPM Platform to Camunda Platform. We only want to do this in places where the name is used descriptively (i.e. not change any code or artifacts).
Related to CAM-12950
=> chore(repo): rename Camunda BPM Platform to Camunda Platform

docs/docs/reference/builtin-functions/feel-built-in-functions-context.md, src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
* add new context built-in functions `put()` and `put all()`
In Zeebe, we can replace the custom `appendTo(x, y)` function by `if (x = null) then y else put all(x, y)`.
closes #169
=> New context built-in functions put()/put all()

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/main/scala/org/camunda/feel/impl/parser/feel-grammar.md, src/test/scala/org/camunda/feel/impl/FeelIntegrationTest.scala
* use common pattern from the parser documentation, for example:
* replace the custom `^^^` operator with `map()` 
* replace the custom `chainl1` method with `flapMap()` 
* use `AnyChar` with negation 
* remove useless logging for invalid date-time formats
Follow-up of #222
=> Simplify the parser

docs/docs/reference/language-guide/feel-data-types.md, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterStringExpressionTest.scala
* allow escape sequences in string literals starting with `\` 
closes #236
=> Allows escape sequences in string literals

pom.xml
* Change the release parent to `camunda-bpm-release-parent`
* Add the property `<skip-third-party-bom>false</skip-third-party-bom>`
* This will generate and publish a `dependencies.txt` file which can be consumed by the Platform Runtime license book generator
closes #249
=> chore(project): generate third-party dependency list

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
* after replacing the parser library in `1.13.0`, some expressions with nested filter and path access can not be parsed anymore (e.g. `([1,2,3,4][item > 2])[1]`, `([{x:{y:1}},{x:{y:2}},{x:{y:3}}]).x[2].y`)
* introduce new parser combinators to parser nested filter and path expressions that follow an expression in brackets
* instead of using a recursive parsing style as it is currently the case, use a continuation parsing style
* this style fits better for parsing an expression from left to right and doesn't require limitations to avoid endless recursions
* since this style seems promising to reduce some limitations of the parser, I plan to roll it out more step-by-step 
closes #258
=> Parse nested path and filter expressions

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
* fix parsing failure if a context literal contains parentheses
* the [cut](https://com-lihaoyi.github.io/fastparse/#Cuts) in the filter expression prevented the parser from backtracking
closes #278
=> Allow parentheses in context literal

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
* fix parser failure that prevented the usage of some/every in a unary-tests expression
* extend the reserved words by `some` and `every` to prevent that a variable can be named as it
closes #280
=> Allow unary-tests expressions with some/every

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala
* fix parsing failure if a filter expression is chained more than two times (e.g. `x[1][2][3]`)
* extend the previous parser approach of continuations by all expressions that can have a continuation 
closes #279
=> Allow chaining of multiple filter expressions

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
* fix a limitation of the parser to write unary-tests expressions with a boolean comparison but without braces
* the problem was caused by the backtracking since the first literal was parsed by `simpleValue`
* help the backtracking by defining that `simplePositiveUnaryTest` is not followed by something else except another `simplePositiveUnaryTest`
closes #109
=> Allow unary-tests without braces

feel-repl.sc
The compilatioin of the feel-repl.sc with Ammonite was throwing some errors due to unspecified or wrong return types.
=> Fix REPL compilation issues

src/main/scala/org/camunda/feel/impl/builtin/StringBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinNumberFunctionTest.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinStringFunctionsTest.scala
* return `null` if the pattern is invalid when invoking one of the functions: split(), matches(), or replace()
* following the DMN spec, a function invocation should return `null` instead of propagating an error
closes #289
=> Return null if the pattern of split(), matches(), or replace() is invalid

pom.xml
* including `fastparse` in the shaded jar can lead to class loading or dependency issues
* avoid these issues by excluding `fastparse` from the shaded jar
closes #328
=> Exclude fastparse dependency from shaded jar

docs/docs/reference/language-guide/feel-context-expressions.md, docs/docs/reference/language-guide/feel-data-types.md, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterLiteralExpressionTest.scala
* update the docs and mention that a context key is either a name or a string
* add a test case for context with string key
closes #296
=> A context key can be a name or a string

docs/versioned_docs/version-1.14/reference/builtin-functions/feel-built-in-functions-context.md, src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
* Adds the support to `m` argument  name to `get entries` builtin function. 
closes #320
=> bug(builtin-function): add 'm' parameter support to get entries

docs/versioned_docs/version-1.14/reference/builtin-functions/feel-built-in-functions-context.md, src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
* Adds `m` and `key` parameters support to `get value`
closes #313
=> bug(builtin-function): add 'm' and 'key' parameters support to get value

src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala
* avoid StackOverflowError if one of the following operations is applied to a huge list (e.g. 10.000 items)
* `filter` 
* `some`
* `every`
* `all()`
* `any()`
* `flatten()`
closes #350
=> Avoid StackOverflowError with huge lists

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterContextExpressionTest.scala
* a list of contexts can be filtered by using the names of the context entries
* additionally, the current item can be accessed under the name 'item'
* avoid that a context value with name 'item' is shadowed by the current item
closes #154
=> Filter a list of contexts by entry with name "item"

src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala
* add a new test case for filtering a list multiple times in a context
closes #356
=> Verify chained list filter in context

docs/docs/reference/builtin-functions/feel-built-in-functions-list.md, src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
* joining function renamed as join
* join function behavior modified to reflect specs (e.g.: empty string and null delimiter management)
* unit tests added
* documentation updated
closes #372
=> fix(builtin-function): joining() function renamed and aligned with join

.github/workflows/build-maven.yml
* add new GitHub action to trigger the Maven build 
* the main purpose is to provide a check for community contributions because they don't trigger the regular CI
none
=> ci(github): new action to build with maven

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterContextExpressionTest.scala
* fix path expression for list of contexts (i.e. list projection) with variable reference
* reuse the existing logic of `path` expressions to avoid duplication and a difference in the behavior 
* it worked previously because it was parsed as a `path` expression instead of a `ref` expression
closes #384
=> fix(engine): list projection with variable

src/test/scala/org/camunda/feel/impl/interpreter/InterpreterFunctionTest.scala
* this adds a unit test for #311.  
Please, mind that I build the test based on [this](https://github.com/camunda/tck/issues/7). There, the function used is:
`number(from: "1.000.000,01", decimal sep:",", grouping sep:".")`
while in the codebase here the expected parameters names are:
- `from`, `decimal separator`, `grouping separator`
This tests the behavior expected by #311.
closes #311
=> chore(interpreter): add a test for whitespaced named parameters

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterContextExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterFunctionTest.scala
* introduces new parsing options for context key names
As you may notice, I slightly changed also the behavior of `private def identifierWithWhitespaces[_: P]: P[String]` since in previous version it supported only names with a single whitespace.
closes #310
=> fix(parser) managing arbitrary names for a context key

docs/docs/changelog/changelog.md, docs/docs/reference/builtin-functions/feel-built-in-functions-numeric.md, docs/docusaurus.config.js, docs/sidebars.js
* add a new section in the docs for the changelog
* add new rounding functions to the docs
* add missing / correct wrong description of numeric functions
closes #393 
closes #387
=> I can see a changelog in the docs

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala
Add `satisfies`, `return`, `then`, `else` as reserved keywords.
closes #394
=> fix(engine): add `satisfies`, `return`, `then`, `else` as reserved keywords

.github/workflows/backport.yml
* add new GitHub workflow to backport PRs
None.
=> Add new workflow for backporting

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterBooleanExpressionTest.scala
* add the reserved keywords: "and", "or" to avoid that a conjunction/disjunction is parsed as a function name
* change the parsing behavior to avoid that a function name contains a reserved keyword like "and" / "or"
* list all built-in function names with keywords explicitly because they don't match the regular function name anymore
closes #397
=> Expression with conjunction/disjunction (and/or) fails if it contains parentheses

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala
Adds `satisfies`, `return`, `then`, and `else` as reserved keywords.
backport of #395
closes #394
=> [Backport 1.14] fix(engine): add reserved keywords 

docs/docs/reference/language-guide/feel-data-types.md, docs/docs/reference/language-guide/feel-temporal-expressions.md, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/main/scala/org/camunda/feel/syntaxtree/ZonedTime.scala, src/test/scala/org/camunda/feel/impl/interpreter/DateTimeDurationPropertiesTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterLiteralExpressionTest.scala
* support the new `@` - notation for temporal values (e.g. `@"2022-04-22"`)
* the new notation is equal to the existing notation using the temporal functions (e.g. `date("2022-04-22")`) 
* update the docs and mention the new notation
Note that I used the existing parser capabilities for temporal values to keep the changes small. At some point, we should refactor how temporal values are parsed. But not now :sweat_smile:  
closes #297
=> Date literal as @ notation

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala
* a list can be filtered using a boolean function
* currently, the function is invoked once to determine if it is a number (for index access) or a boolean value (or something else)
* since the function is invoked without the list item, the invocation can fail if the "item" variable is passed in as a parameter
* fix the issue by avoiding the function invocation without "item" variable in the context
closes #359
=> Filter list with custom function

src/main/scala/org/camunda/feel/impl/interpreter/ObjectContext.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterBeanExpressionTest.scala
* an expression can access the properties of a bean via field or method lookup 
* ignore methods with parameters when resolving available fields of a bean
closes #413
=> Builder-style method is used instead of getter

src/main/scala/org/camunda/feel/impl/DefaultValueMapper.scala, src/test/scala/org/camunda/feel/api/valuemapper/BuiltinValueMapperOutputTest.scala
* return a time with zone id/offset as `java.time.OffsetTime` instead of custom `ZonedTime`
closes #163
=> Return time with zone id/offset as OffsetTime

docs/docs/reference/builtin-functions/feel-built-in-functions-boolean.md, docs/docs/reference/builtin-functions/feel-built-in-functions-context.md, docs/docs/reference/builtin-functions/feel-built-in-functions-conversion.md, docs/docs/reference/builtin-functions/feel-built-in-functions-introduction.md, docs/docs/reference/builtin-functions/feel-built-in-functions-list.md, docs/docs/reference/builtin-functions/feel-built-in-functions-numeric.md, docs/docs/reference/builtin-functions/feel-built-in-functions-range.md, docs/docs/reference/builtin-functions/feel-built-in-functions-string.md, docs/docs/reference/builtin-functions/feel-built-in-functions-temporal.md, docs/docs/reference/language-guide/feel-boolean-expressions.md, docs/docs/reference/language-guide/feel-context-expressions.md, docs/docs/reference/language-guide/feel-control-flow.md, docs/docs/reference/language-guide/feel-data-types.md, docs/docs/reference/language-guide/feel-expressions-introduction.md, docs/docs/reference/language-guide/feel-functions.md, docs/docs/reference/language-guide/feel-list-expressions.md, docs/docs/reference/language-guide/feel-numeric-expressions.md, docs/docs/reference/language-guide/feel-string-expressions.md, docs/docs/reference/language-guide/feel-temporal-expressions.md, docs/docs/reference/language-guide/feel-unary-tests.md, docs/docs/reference/language-guide/feel-variables.md, docs/docs/reference/language-guide/language-guide-introduction.md, docs/docs/reference/what-is-feel.md
* apply changes from camunda-platform-docs downstream project (see [PR](https://github.com/camunda-cloud/camunda-cloud-documentation/pull/543))
* but don't apply all changes, especially in the FEEL expressions, because they are not correct
closes #407
=> doc: apply changes from downstream project

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
* a unary-tests expression with a boolean literal and a conjunction/disjunction failed to parse
* the parser expected no other chars (EOF) after the boolean literal was accepted
* adjust the parser to accept the boolean literal only at the end of the expression (EOF)
closes #429
=> Parse unary-tests expression with boolean and conjunction/disjunction 

.github/dependabot.yml, .github/workflows/project-new-issues.yml
* Bump add-to-project to version v0.1.0
* Have dependabot create PR's for outdated actions
=> Dependabot analyse GHA workflows

pom.xml
* the reduced pom overrides the original pom when installing the artifacts
* avoid creating a reduced pom to fix the issue
* in a previous version of the plugin (3.2.4), no reduced pom was created
closes #450
=> build: avoid creating a reduced pom

pom.xml
related to a change that was announced a while ago https://camunda.com/blog/2022/03/a-new-domain-name-for-camunda-artifactory/
We're still seeing a lot of traffic from the machine-account user that is linked to the repository (ci-cambpm --> due to running on the ci.cambpm Jenkins)
closes #
=> chore: switch to non deprecated URL

docs/docs/tutorial/tutorial-2-1.mdx, docs/src/components/EnvelopeAddress.js, docs/src/components/LiveFeel.js
* Makes the AddressEnvelop configurable from outside with:
* a default feel expression
* a feel context
* metadata about the page
* Reuses the LiveFeel component to evaluate the expression inside the AddressEnvelop
* Deletes a lot of redundant code
Summer hackdays 🦖
=> Use LiveFeel component for the AddressEnvelop

docs/src/components/LiveFeel.js
The new domain name `feel-service.camunda.com` for the feel tutorial backend is ready to use!
=> docs: change to use `feel-service.camunda.com` domain name

docs/src/components/LiveFeel.js
* Small change to `LiveFeel.js` to look at "error" rather than "result" in order to know whether or not to display error. This way, expressions that legitimately evaluate to `false` will be displayed in playground results. 
closes #504
=> docs: fix #504, playground can't display legitimate false return values

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala
- if the filter of a list returns a number then the expression should return the item at the given index
- note that the code could look more elegant but we want to avoid unintended function invocation because the invocations are visible by the function provider (https://github.com/camunda/feel-scala/issues/359)
- we could improve the code later if the function defines the types of the arguments and the return value (https://github.com/camunda/feel-scala/issues/295)
closes #507
=> fix: filter expression with numeric function

docs/docs/reference/language-guide/feel-boolean-expressions.md, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
*  instance of doesn't work for durations 
Expected behavior
null instance of years and months duration -> false
null instance of days and time duration -> false
duration("P3M") instance of years and months duration -> true
duration("PT4H") instance of days and time duration -> true
closes #155
=> fix: Instance of with correct duration names

src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
Add a test case to verify that a value in a unary-tests expression can be compared to a variable with a list value.
Verifies that #308 is fixed (since version `1.14.0`).
=> test: verify unary-tests with list variable

.github/ISSUE_TEMPLATE/new-release.md, docs/docusaurus.config.js, docs/versioned_docs/version-1.15/playground/playground.mdx, docs/versioned_docs/version-1.15/tutorial/tutorial-1-1.mdx, docs/versioned_docs/version-1.15/tutorial/tutorial-1-2.mdx, docs/versioned_docs/version-1.15/tutorial/tutorial-1-3.mdx, docs/versioned_docs/version-1.15/tutorial/tutorial-2-1.mdx, docs/versioned_docs/version-1.15/tutorial/tutorial-3-1.mdx, docs/versioned_docs/version-1.15/tutorial/tutorial-3-2.mdx, docs/versioned_docs/version-1.15/tutorial/tutorial-4-1.md, docs/versioned_docs/version-1.15/tutorial/tutorial.mdx, docs/versioned_sidebars/version-1.15-sidebars.json
Set the last version to the last released version, instead of the current dev version. This changes the behavior to redirect by default to the last released version. In most cases, this should be the version that users are looking for.
Disable the "unmaintained version" for the last released version (1.15) and all supported versions (1.14).
For reference: https://docusaurus.io/docs/versioning#configuring-versioning-behavior.
---
--- 
---
=> docs: Update version banner

pom.xml, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala
Backport of #523 to `1.14`.
relates to camunda/camunda-bpm-platform#2818
=> [Backport 1.14] chore(deps): bump scala-library from 2.13.8 to 2.13.9

docs/versioned_docs/version-1.14/reference/builtin-functions/feel-built-in-functions-boolean.md, docs/versioned_docs/version-1.14/reference/builtin-functions/feel-built-in-functions-context.md, docs/versioned_docs/version-1.14/reference/builtin-functions/feel-built-in-functions-string.md, docs/versioned_docs/version-1.14/reference/language-guide/feel-variables.md, docs/versioned_docs/version-1.15/reference/builtin-functions/feel-built-in-functions-boolean.md, docs/versioned_docs/version-1.15/reference/builtin-functions/feel-built-in-functions-context.md, docs/versioned_docs/version-1.15/reference/builtin-functions/feel-built-in-functions-string.md, docs/versioned_docs/version-1.15/reference/language-guide/feel-variables.md
Add markers for all Camunda extensions in the docs for versions 1.15 and 1.14.
Backport of #550
=> docs: mark Camunda extensions in versions 1.15 and 1.14

docs/docs/reference/builtin-functions/feel-built-in-functions-context.md, src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
- Add the new function `context put(context: context, key: string, value: Any): context` from DMN 1.4 
- Replaces the previous function [put()](https://camunda.github.io/feel-scala/docs/reference/builtin-functions/feel-built-in-functions-context/#put)
- Keep the previous function for backward compatibility 
- Mark the previous function as deprecated in the docs 
- Add the new function `context put(context: context, keys: list<string>, value: Any): context` from DMN 1.4 
- It has the same name as the function above but a different signature
- It allows to add a nested entry to the context 
- Add the new function `context merge(contexts: list<context>): context` from DMN 1.4 
- Replaces the previous function [put all()](https://camunda.github.io/feel-scala/docs/reference/builtin-functions/fe …
=> Support built-in functions `context put()` and `context merge()`

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/DateTimeDurationPropertiesTest.scala
`x.time offset` would fail parsing. It considered the variable to be `x.time`. The parser would then not be able to parse ` offset`.
closes #547
=> Fix parsing `time offset` of variable

docs/docs/reference/language-guide/feel-boolean-expressions.md, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
Use the correct type name `date and time` for the `instance of` expression. Previously, it uses the wrong type name [date time](https://camunda.github.io/feel-scala/docs/reference/language-guide/feel-boolean-expressions#instance-of).
```
// DMN compliant 
@"2018-12-08T10:30:11" instance of date and time
// vs.
// not DMN compliant
@"2018-12-08T10:30:11" instance of date time
```
Support the previous type name for backward compatibility.
closes #543
=> instance-of doesn't work for the type "date and time"

docs/docs/reference/language-guide/feel-functions.md, docs/versioned_docs/version-1.14/reference/language-guide/feel-functions.md, docs/versioned_docs/version-1.15/reference/language-guide/feel-functions.md
Describe the result of a function invocation if the argument types don't match the signature.
contributes to #581
=> docs: function invocation with wrong argument types

docs/docs/reference/builtin-functions/feel-built-in-functions-boolean.md, docs/docs/reference/builtin-functions/feel-built-in-functions-context.md, docs/docs/reference/builtin-functions/feel-built-in-functions-conversion.md, docs/docs/reference/builtin-functions/feel-built-in-functions-list.md, docs/docs/reference/builtin-functions/feel-built-in-functions-numeric.md, docs/docs/reference/builtin-functions/feel-built-in-functions-range.md, docs/docs/reference/builtin-functions/feel-built-in-functions-string.md, docs/docs/reference/builtin-functions/feel-built-in-functions-temporal.md, docs/docs/reference/language-guide/feel-boolean-expressions.md, docs/docs/reference/language-guide/feel-functions.md, docs/docs/reference/language-guide/feel-string-expressions.md, docs/docs/reference/language-guide/feel-variables.md
Split the built-in functions in the docs by their signature.
---
---
closes #555
=> docs: split functions by their signatures 

docs/docs/reference/builtin-functions/feel-built-in-functions-context.md, src/main/scala/org/camunda/feel/FeelEngine.scala, src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/BuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/FeelIntegrationTest.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
Add a new get value function with a new signature. With this function, a user can dynamically pass a path to obtain a nested property in a given context.
closes [#11293](https://github.com/camunda/zeebe/issues/11293)
=> Add new get value function with dynamic path

docs/docs/reference/builtin-functions/feel-built-in-functions-numeric.md, docs/versioned_docs/version-1.15/reference/builtin-functions/feel-built-in-functions-numeric.md, docs/versioned_docs/version-1.16/reference/builtin-functions/feel-built-in-functions-numeric.md
The docs contain rounding functions without a scala parameter. But these functions are not available and not part of the DMN standard.
=> docs: Remove unavailable rounding functions

docs/docs/reference/builtin-functions/feel-built-in-functions-conversion.md, docs/docs/reference/builtin-functions/feel-built-in-functions-list.md, docs/docs/reference/builtin-functions/feel-built-in-functions-numeric.md, docs/docs/reference/builtin-functions/feel-built-in-functions-range.md, docs/docs/reference/builtin-functions/feel-built-in-functions-temporal.md
There were a few problems regarding:
- wording ("month of year", not "month of week")
- whitespaces
- typo (treu)
- wrong examples (outcome different as stated, keys in contexts are strings)
closes #
=> docs: Fix descriptions and examples

docs/versioned_docs/version-1.15/reference/builtin-functions/feel-built-in-functions-conversion.md, docs/versioned_docs/version-1.15/reference/builtin-functions/feel-built-in-functions-list.md, docs/versioned_docs/version-1.15/reference/builtin-functions/feel-built-in-functions-range.md, docs/versioned_docs/version-1.15/reference/builtin-functions/feel-built-in-functions-temporal.md, docs/versioned_docs/version-1.16/reference/builtin-functions/feel-built-in-functions-conversion.md, docs/versioned_docs/version-1.16/reference/builtin-functions/feel-built-in-functions-list.md, docs/versioned_docs/version-1.16/reference/builtin-functions/feel-built-in-functions-numeric.md, docs/versioned_docs/version-1.16/reference/builtin-functions/feel-built-in-functions-range.md, docs/versioned_docs/version-1.16/reference/builtin-functions/feel-built-in-functions-temporal.md
Backport changes of #645 to `1.16` and `1.15`.
related to #645
=> [Backport] docs: fix descriptions and examples

pom.xml, src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala, src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/DateTimeDurationPropertiesTest.scala
Backport of #636 to `1.16`.
relates to #631
=> [Backport 1.16] fix(builtin-function): fix string conversion of years-months-durations

src/main/scala/org/camunda/feel/FeelEngine.scala, src/main/scala/org/camunda/feel/impl/interpreter/EvalContext.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/FeelIntegrationTest.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
Fix an issue that did not store the context entries in the same order as defined in the literal (i.e. `{a: 1, b: 2}` is stored as `{b: 2, a: 1}`). The issue could be observed by using the `get entries()` function.
The root cause was not in the context functions but in how the context is created in the engine via `EvalContext`. Fixing the behavior by using a sorted map for storing the context entries and by avoiding the nesting of the `VariableProvider`s.
As a result, the code of the `EvalContext` is a bit more complex but easier to debug. All variables and functions are stored in one provider instead of a chain with one provider per variable/function.
closes #161 
based on a previous try #340
=> fix: Preserve the order of a context

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/api/valuemapper/BuiltinValueMapperInputTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterNonExistingVariableExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterNumberExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
This PR is a WIP. A bunch of tests are still failing
Before when we encountered a non-existing variable in a comparison it would result in an error: "no variable found for name 'x'".
This commit changes this so we can deal with non-existing variables. They now get treated as ValNull and the comparison succeeds without errors.
Fixes part of #582
=> Handle non-existing variable in comparison

src/test/scala/org/camunda/feel/impl/interpreter/EvaluationErrorMatcher.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
This test should verify that a variable should not be allowed to be a key word. This should fail at parse time.
As we only checked if it returned an ValError this all succeeded. However, this is not accurate as the error wasn't always thrown at parse-time.
What would happen is that the expression got evaluated. It turned out the variable didn't exist and also throw the ValError. This means the assertion would succeed, but the test would actually be a false-positive.
With this custom matcher we can verify that we actually get the error we expect, by verifying if it's a parse error or not.
The keywords that have not been listed are now added to an ignore test case.
I tried adding the missing key words to the list and that broke a lot of tests. I figured there was a reason why they weren't …
=> Fix variable name should not be keyword test

.github/workflows/build-docs.yaml, .github/workflows/build-maven.yml
Follow the [guide](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions) to enable merge queues.
=> ci: Enable GitHub CI for merge-group

docs/docs/reference/builtin-functions/feel-built-in-functions-list.md, src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
* Add tests
* Create a function to find duplicates.
* Add test case for named list parameters.
closes #642
=> Add new built in function to find duplicates

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterNumberExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
Align the behavior of unary-tests with a comparison to `null`. In both cases, the engine returns `null`. 
For example, the evaluation of `< 3` with `null` as the input value returns `null`. Same as the comparison `null < 3` returns `null`. 
Fixing the behavior in the parser by introducing a special case for simple-positive-unary-test (i.e. comparison with the input value).
closes #679
=> fix: Unary-test expression with null value

docs/docs/reference/builtin-functions/feel-built-in-functions-boolean.md, src/main/scala/org/camunda/feel/impl/builtin/BooleanBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinFunctionTest.scala
Create a new function `get or else()` in order to allow users to easily deal with optional value, this new fucntion accept two parameters:
- value -> the optional value to check
- default -> the default value to return in case the first parameter is null
closes #618
=> New function get or else()

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala
This changes the behavior of filter expressions to be more lenient.
Filter expressions now filter the list even when the filter expression is not evaluating to a boolean (for item comparison) or a number (for direct access).
When the filter expression would previously cause an error, the error is now suppressed and a list with only those values that match the filter expression is returned.
Please note that this pull request does not fully resolve issue #582. It does not yet deal with lists of contexts where the filter expression refers to missing properties of those contexts. This should be resolved in another pull request.
partially deals with #582 (filters over context lists are not yet covered)
=> Improve null handling in filter expressions

src/main/scala/org/camunda/feel/api/EvaluationFailure.scala, src/main/scala/org/camunda/feel/impl/interpreter/EvalContext.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/EvaluationResultMatchers.scala, src/test/scala/org/camunda/feel/impl/FeelEngineTest.scala, src/test/scala/org/camunda/feel/impl/SuppressedFailuresTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterFunctionTest.scala
* Change the behavior of the engine if an expression invokes a non-existing function. Instead of failing the evaluation, the invocation returns `null`. 
* Additionally, the evaluation reports a failure that the function doesn't exist. 
* Extend and refactor the test cases for the function invocation to verify the evaluation result and the reported failures.
closes #670
=> feat: The invocation of a non-existing function returns null

.github/workflows/build-maven.yml, .github/workflows/release.yml, pom.xml, src/main/scala/org/camunda/feel/FeelEngineClock.scala, src/main/scala/org/camunda/feel/api/EvaluationFailure.scala, src/main/scala/org/camunda/feel/api/EvaluationFailureType.scala, src/main/scala/org/camunda/feel/api/EvaluationResult.scala, src/main/scala/org/camunda/feel/api/FeelEngineApi.scala, src/main/scala/org/camunda/feel/api/FeelEngineBuilder.scala, src/main/scala/org/camunda/feel/api/ParseResult.scala, src/main/scala/org/camunda/feel/impl/builtin/BooleanBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/builtin/BuiltinFunction.scala, src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/builtin/NumericBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/builtin/RangeBuiltinFunction.scala, src/main/scala/org/camunda/feel/impl/builtin/StringBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/builtin/TemporalBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/EvaluationFailureCollector.scala, src/main/scala/org/camunda/feel/syntaxtree/ConstRangeBoundary.scala, src/main/scala/org/camunda/feel/syntaxtree/RangeBoundary.scala, src/test/scala/org/camunda/feel/api/context/SimpleTestContext.scala, src/test/scala/org/camunda/feel/impl/EvaluationResultMatchers.scala, src/test/scala/org/camunda/feel/impl/SuppressedFailuresTest.scala, src/test/scala/org/camunda/feel/impl/TimeTravelClock.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinRangeFunctionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/EvaluationErrorMatcher.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterNonExistingVariableExpressionTest.scala, src/test/scala/org/camunda/feel/impl/script/PinnedClock.scala
* Fix the license Maven plugin configuration
* Adjust the build pipeline to check for license headers
* Add missing license headers
=> build: Fix licence check

src/test/scala/org/camunda/feel/impl/interpreter/InterpreterContextExpressionTest.scala
This PR adds some testcases to verify filtering over a list of contexts works as intended. It focuses on cases where something in the contexts, or filter is non-existing or null. 
closes #582
=> Verify filtering list of contexts where some part is null or non-existing

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/EvaluationResultMatchers.scala, src/test/scala/org/camunda/feel/impl/SuppressedFailuresTest.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinFunctionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterBeanExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterContextExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala
* Change the behavior to return `null` if a context doesn't contain an entry with the given key, or if the context is null. Previously, the evaluation failed in this case.
* Write new test cases and adjust the expected behavior of existing test cases. Use the new evaluation result matcher in all test cases to verify reported failures, improve readability, and align the testing style.  
contributes to #674
=> feat: Non-existing context entries result in `null`

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/api/FeelEngineTest.scala, src/test/scala/org/camunda/feel/api/context/CustomContextTest.scala, src/test/scala/org/camunda/feel/impl/FeelEngineTest.scala, src/test/scala/org/camunda/feel/impl/SuppressedFailuresTest.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinFunctionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterNonExistingVariableExpressionTest.scala, src/test/scala/org/camunda/feel/impl/script/ScriptEngineTest.scala, src/test/scala/org/camunda/feel/impl/script/UnaryTestsScriptEngineTest.scala
Change the behavior of the FEEL engine to replace a non-existing variable and a non-existing input value with `null`. Previously, the evaluation failed in these cases. 
A note to the reviewer, the actual code fix is very small. The major changes are refactorings in the test classes to adopt the new test style. 
closes #674
=> feat: Handle non-existing variables

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/DateTimeDurationPropertiesTest.scala
Change the behavior for accessing a non-existing property. Instead of failing the evaluation, it returns `null`. A failure with a descriptive message is reported.
This change is aligned with the DMN specification and the new direction to be more null-friendly.
closes #707
=> feat: Return null on accessing a non-existing property

.ci.cambpm, .github/workflows/build-maven.yml, pom.xml
* bump the release parent version to pick up the source code level changes
* test feel-scala with JDK 11 and 17
https://github.com/camunda/camunda-bpm-platform/issues/3690
=> chore(project): use jdk 11 source code level

src/main/scala/org/camunda/feel/impl/interpreter/EvalContext.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/api/FeelEngineTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/ComparisonTypeTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterContextExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala
If an expression or a unary-test compares two values of different types then the evaluation returns null and reports a failure. Previously, the evaluation failed with an error.
The new behavior is aligned with the DMN specification and helps users to handle these cases.
closes #708
=> feat: Comparing different types returns null

docs/docs/reference/builtin-functions/feel-built-in-functions-boolean.md, src/main/scala/org/camunda/feel/impl/builtin/BooleanBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinFunctionsTest.scala
Change the behavior of the function `is defined()` to return `true` if the value is not `null`. Previously, the function returned `true` if the value was `null`. It returned `false` if the value was a non-existing variable or context entry (i.e. a ValError).
The changes in the null-handling of the FEEL engine to replace a non-existing variable or context entry with `null` made this function useless. It returned always `true`.
A complete fix of the function is not possible because of the new null-handling. However, this change in the semantics of the function reduces the impact on the users (i.e. the regression).
The function still works as before for non-existing variables and context entries. But it may break for variables and context entries with a `null` value. See …
=> fix: `is defined()` function returns false if the value is null 

pom.xml
Released a new version `1.17.0-rc1`.
Fixing the build by downgrading the `maven-javadoc-plugin` to version `2.9.1`.
=> build: Released version `1.17.0-rc1`

.ci.cambpm, .github/workflows/build-maven.yml, pom.xml
Backport of https://github.com/camunda/feel-scala/pull/716 for version `1.16`.
related to https://github.com/camunda/camunda-bpm-platform/issues/3690
=> [Backport 1.16] update to Java 11 source code level

pom.xml, src/main/scala/org/camunda/feel/impl/builtin/BuiltinFunction.scala, src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/test/scala/org/camunda/feel/api/StringRepresentationTypeTest.scala, src/test/scala/org/camunda/feel/impl/SuppressedFailuresTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/ComparisonTypeTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/DateTimeDurationPropertiesTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterContextExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterFunctionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala
* Uniform the failure messages and add missing failure types.
* Copy the existing string representation logic of the `string()` function into the value types.
closes #713
=> feat: Make failure messages more readable

.ci.cambpm, .github/workflows/build-maven.yml, pom.xml
This reverts commit 0134bada883c742534bfc29cdbb2394288919ee3.
* Cammunda Platform 7.19 uses 1.15.3 therefore we want to leave the source code changed
related to https://github.com/camunda/camunda-bpm-platform/issues/3690
=> revert(project): update to Java 11 source code level

pom.xml
* Downport javadoc plugin version to 2.9.1 to avoid errors that appear with higher version
https://github.com/camunda/camunda-bpm-platform/issues/3690
=> chore(deps): downport the javadoc plugin version to 2.9.1

.ci.cambpm, pom.xml
* ci: add javadoc
* disable failure on error for javadoc => the javadocs won't be built but it's only one class so we can use this as workaround until the javadoc failure is fixed
https://github.com/camunda/camunda-bpm-platform/issues/3690
=> chore(ci): disbale fail on error for the javadoc 

docs/docs/reference/builtin-functions/feel-built-in-functions-boolean.md
Correct the example of the `get or else()` function in the doc.
=> fix: typos

src/main/scala/org/camunda/feel/api/FeelEngineApi.scala, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterStringExpressionTest.scala
This PR changes the evaluation of escape characters within a string. Instead of escaping those characters now are translated.
closes #701
=> fix: string escape characters

src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala
Add test cases to verify that the string() function returns the string representation for list and context values.
closes #650
=> test: Verify string() with list/context value

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterStringExpressionTest.scala
Handle double quotes in string literals properly. Currently, the quotes are escaped but should not.
```
// expression:
"hello \"FEEL\"!"
// result in current version: 
"hello \\\"FEEL\\\"!"
// result with the change:
"hello \"FEEL\"!"
```
closes #778
=> fix: Double quotes in string literal are escaped

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterStringExpressionTest.scala
Backport of #780 to `1.16`.
relates to #778
=> [Backport 1.16] fix: Double quotes in string literal are escaped

src/main/scala/org/camunda/feel/impl/interpreter/EvalContext.scala, src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterContextExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/MyCustomContext.scala
Fix the variable resolution if the variables are provided by a custom context. 
Currently, the local variables within a list filter or a context literal are overridden by variables from the custom context.  
closes #765 
closes #774
=> fix: Variable resolution for custom context

.github/workflows/backport.yml
Use a separate PAT token for the backport action.
Previously, the action used the default token. As a disadvantage, the PR of the backport action didn't trigger other Github workflows, for example, to run the tests.
=> ci: Use a separate token for backport action

.github/workflows/build-maven.yml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4058
=> chore(workflows): Add Java 21 to build-maven.yml

docs/src/components/LiveFeel.js, docs/src/components/LiveFeelUnaryTests.js
Modify the FEEL Playground to evaluate an expression if no/empty context is entered. 
closes https://github.com/camunda-community-hub/feel-scala-playground/issues/47
=> doc(playground): Evaluate expression with empty context

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterInterruptionTest.scala
This simple change allows long-running feel evaluation/parsing processes to be gracefully interrupted. Consumers can execute the FEEL engine parsing/evaluations on a separate thread and be able to cancel them interruptedly.
closes #823
=> feat: I can interrupt an expression evaluation

src/main/scala/org/camunda/feel/impl/builtin/StringBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinStringFunctionsTest.scala
Add the following built-in function `trim()`
```
// examples
trim("hello world")    // --> "hello world"
trim("hello world  ")    // --> "hello world"
trim("  hello world")    // --> "hello world"
trim("  hello world  ")    // --> "hello world"
trim(" hello   world ")    // --> "hello   world"
```
closes #815
=> feat: add trim() function for whitespace stripping

pom.xml, src/main/scala/org/camunda/feel/impl/builtin/StringBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinStringFunctionsTest.scala
Add the following built-in function `uuid()`.
```
// function signature
uuid(): String
// usage
uuid()    // -> "7793aab1-d761-4d38-916b-b7270e309894"
uuid()    // -> "df09d5c2-e9f0-432d-9027-aaa5db56b8b5"
```
closes #796
=> feat: add built-in function to generate a UUID string

src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/BuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala
Backport of #833 to `1.17`.
relates to #804
original author: @mustafadagher
=> [Backport 1.17] fix: `string()` function can handle a context with custom value types

.mvn/wrapper/maven-wrapper.properties
* Update Maven wrapper from `3.5.4` to `3.9.6`
* Fixes build issues with `maven-jar-plugin:3.4.1` that requires Maven version `3.6.3`
=> ci: Update Maven wrapper to 3.9.6

src/main/scala/org/camunda/feel/impl/builtin/StringBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinStringFunctionsTest.scala
Add function to encode a string as base64
closes #846
=> feat: add built-in function to encode a string as base64

src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
Backport of #858 to `1.17`.
relates to #856
=> [Backport 1.17] fix: Invoke context() function with a list containing a custom context

src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
Backport of #858 to `1.16`.
relates to #856
=> [Backport 1.16] fix: Invoke context() function with a list containing a custom context

pom.xml, src/main/scala/org/camunda/feel/api/FeelEngineBuilder.scala, src/test/java/org/camunda/feel/api/FeelEngineBuilderJava.java, src/test/java/org/camunda/feel/api/FeelEngineBuilderTest.java, src/test/scala/org/camunda/feel/api/FeelEngineBuilderTest.scala
Refactored implementation
closes #724
=> feat: Make the FeelEngineBuilder available from Java/Kotlin

src/main/scala/org/camunda/feel/api/FeelEngineBuilder.scala, src/test/java/org/camunda/feel/api/FeelEngineBuilderJava.java, src/test/scala/org/camunda/feel/api/FeelEngineBuilderTest.scala
Follow-up of #832.
- Move the Java builder method to the root 
- Add JavaDoc
- Extend the test cases for the Java builder
related to #724
=> refactor: FeelEngineBuilder for Java usage

src/main/scala/org/camunda/feel/impl/builtin/StringBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinStringFunctionsTest.scala
Fix the behavior of the function `substring()`. If the given length is greater than the string, return the remaining characters from the start index instead of throwing an exception.  
closes #801
=> fix: substring() with exceeding length

src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala
Fix the `number()` function to return `null` if the given string is invalid. Before the evaluation failed with an exception. 
closes #731
=> fix: number() to return null if the given string is invalid

src/main/scala/org/camunda/package.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterLiteralExpressionTest.scala
Adjust the behavior of date and date-time literals and conversion functions to return `null` if the date is invalid. Previously, it returned the last day of the month. 
For example:
- `2023-02-29` is invalid because 2023 is not a leap year
- `2023-06-31` is invalid because June has only 30 days
closes #867
=> fix: Return `null` if a date is invalid

src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala
Backport of #892 for `1.17`.
closes #731
=> [Backport 1.17] fix: number() to return null if the given string is invalid

src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala
Backport of #892 for `1.16`.
Additionally to the changes in the original, this PR contains the migration of the test class to the new test style. This migration was necessary to cherry-pick the commit with the new test cases.
closes #731
=> [Backport 1.16] fix: number() to return null if the given string is invalid

src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
Fix the function `context put()` if more than two keys are passed as arguments.
We had an issue in the recursion and forgot to pass the context updater function with us. As a result, this worked only for one or two keys. :loop: 
closes #835
=> fix: Function `context put()` works for more than two keys

src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
Backport of #902 to `1.16`.
relates to #835
=> [Backport 1.16] fix: Function `context put()` works for more than two keys

src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
Backport of #902 to `1.17`.
relates to #835
=> [Backport 1.17] fix: Function `context put()` works for more than two keys

src/main/scala/org/camunda/feel/FeelEngine.scala, src/main/scala/org/camunda/feel/impl/DefaultValueMapper.scala, src/main/scala/org/camunda/feel/impl/builtin/BuiltinFunction.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/test/scala/org/camunda/feel/api/StringRepresentationTypeTest.scala, src/test/scala/org/camunda/feel/impl/FeelEngineTest.scala, src/test/scala/org/camunda/feel/impl/SuppressedFailuresTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
Fix the behavior of unary-test expressions if the special input variable `?` is used to access the input value. From the following definition, the current behavior is incorrect in case d).
**Key idea:**
- Distinguish the case d) from the other cases  
- Limit the access to the special input variable `?` to unary-tests
- Introduce a new error value type to detect the access of `?` and interrupt the evaluation
**Reviewer hint:** 
The first 3 commits are the most relevant. The rest contains a lot of refactoring and may be harder to compare with the original code.
closes #864
=> fix: Unary-test behavior with special input variable `?`

src/main/scala/org/camunda/feel/FeelEngine.scala, src/main/scala/org/camunda/feel/impl/DefaultValueMapper.scala, src/main/scala/org/camunda/feel/impl/builtin/BuiltinFunction.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/test/scala/org/camunda/feel/api/StringRepresentationTypeTest.scala, src/test/scala/org/camunda/feel/impl/FeelEngineTest.scala, src/test/scala/org/camunda/feel/impl/SuppressedFailuresTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
Backport of #887 to `1.17`.
relates to #864
=> [Backport 1.17] fix: Unary-test behavior with special input variable `?`

src/main/scala/org/camunda/package.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterLiteralExpressionTest.scala
Backport of #889 for `1.17`.
closes #867
=> [Backport 1.17] fix: Return null if a date is invalid

src/main/scala/org/camunda/package.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterLiteralExpressionTest.scala
Backport of #889 for `1.16`.
closes #867
=> [Backport 1.16] fix: Return null if a date is invalid

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala
Adjust the behavior to return `null` if a list operation (filter, access, some, every) is applied to a value that is not a list.
closes #809
=> fix: List operation returns null if the value is not a list

pom.xml, src/main/scala/org/camunda/feel/FeelEngine.scala, src/main/scala/org/camunda/feel/impl/DefaultValueMapper.scala, src/main/scala/org/camunda/feel/impl/builtin/BuiltinFunction.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/test/scala/org/camunda/feel/api/FeelEngineTest.scala, src/test/scala/org/camunda/feel/impl/FeelEngineTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/DateTimeDurationPropertiesTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterBeanExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterContextExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterListExpressionTest.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
Backport of #887 for `1.16`.
Most changes are the same as in the original. However, I had to adjust the code to align with the error behavior in version `1.16.`. Instead of returning `null` (e.g. if a variable doesn't exist), the evaluation fails or returns `false`. The last commit highlights the different behavior for unary-tests compared to version `1.17+`. 
closes #864
=> [Backport 1.16] fix: Unary-test behavior with special input variable `?`

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
Adjust the parsing of a variable name. If the name starts with a key word, like "in", it can continue with a number.
Previously, the key word must be followed by a letter.
closes #873
=> fix: Variable name starting with "in"

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
Backport of #909 to `1.16`.
relates to #873
=> [Backport 1.16] fix: Variable name starting with "in"

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
Backport of #909 to `1.17`.
relates to #873
=> [Backport 1.17] fix: Variable name starting with "in"

src/main/scala/org/camunda/feel/impl/builtin/StringBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinStringFunctionsTest.scala
Backport of #893 for `1.16`.
closes #801
=> [Backport 1.16] fix: substring() with exceeding length

src/main/scala/org/camunda/feel/impl/builtin/StringBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinStringFunctionsTest.scala
Backport of #893 for `1.17`.
closes #801
=> [Backport 1.17] fix: substring() with exceeding length

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/main/scala/org/camunda/feel/impl/parser/FeelWhitespace.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterExpressionTest.scala
Adjust the parser's whitespace handling to ignore FEEL-specific whitespace characters, such as NBSP (i.e. Non-breaking space / `\u00A0`),  as defined in the DMN specification.
The `JavaWhitespace` class worked very well because it also supported Java-like comments, as required by the DMN specification. Instead of adding additional whitespace rules for the individual parsers, extend the `JavaWhitespace` class by making a copy of it. :see_no_evil: This should be less error-prone, easier to maintain, and more efficient. :angel: 
closes #840
=> fix: Parse expression with NBSP character

src/main/scala/org/camunda/feel/FeelEngine.scala, src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/BuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/impl/interpreter/ValComparator.scala, src/test/scala/org/camunda/feel/impl/FeelIntegrationTest.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
Fixes the detection of duplicated context values in the functions:
- `distinct values()`
- `union()`
- `duplicate values()`
closes #771 
closes #772 
closes #773
=> fix: Detect duplicated context values in `distinct values()` + `union()` + `duplicate values()` 

src/main/scala/org/camunda/feel/FeelEngine.scala, src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/BuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/impl/interpreter/ValComparator.scala, src/test/scala/org/camunda/feel/impl/FeelIntegrationTest.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
Backport of #908 for `1.17`.
closes #771
closes #772
closes #773
=> [Backport 1.17] fix: Detect duplicated context values in `distinct values()` + `union()` + `duplicate values()`

src/main/scala/org/camunda/feel/FeelEngine.scala, src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/BuiltinFunctions.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/main/scala/org/camunda/feel/impl/interpreter/ValComparator.scala, src/test/scala/org/camunda/feel/impl/FeelIntegrationTest.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
Backport of #908 for `1.16`.
All changes are the same as in the original, except there is no function `duplicate values()` in version `1.16`. 
closes #771
closes #772
=> [Backport 1.16] fix: Detect duplicated context values in `distinct values()` + `union()`

README.md
I got a 404 when clicking on the link before.
* Correct the link to the developer docs. It's the only doc about extending the FEEL engine.
closes #
=> correct link to developer docs

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterStringExpressionTest.scala
Backport of #930 to `1.17`.
relates to #883 #879
=> [Backport 1.17] fix: Handle escape and regex characters

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterStringExpressionTest.scala
Backport of #930 to `1.18`.
relates to #883 #879
=> [Backport 1.18] fix: Handle escape and regex characters

src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterStringExpressionTest.scala
Backport of #930 to `1.16`.
relates to #883 #879
=> [Backport 1.16] fix: Handle escape and regex characters

src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
* This PR adds a built in list function `partition(list, size)`. 
* Support for splitting an array into equals sub arrays each with the maximum number of elements defined by the `size` argument.  
closes #881
=> feat(builtin): add partition function

src/main/scala/org/camunda/feel/FeelEngine.scala
This PR lowers the log level of the initial engine creation log statement. The reasoning here is that almost all of the information provided here is only really useful for debugging, and generally not useful for the common user.
As this is mostly to reduce the noise-to-signal ratio in Zeebe, the alternative would be only showing WARN messages from this library (as we do with other libraries). That would also be acceptable to me, so feel free to reject this if you disagree, and we can go with the alternative :)
closes camunda/camunda#26395
=> refactor: lower log level to debug

src/main/scala/org/camunda/feel/impl/builtin/BuiltinFunction.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
The engine restricts the usage of `?` to an unary-test expression. It is implemented by returning a `ValFatalError` when accessing `?`. If the expression is a unary-test, it evaluates the expression again and assigns the input value to `?`.  
Previously, the engine invoked a function without checking the arguments before. As a result, a function with an `Any` parameter (e.g. `list contains(list, any)`) accepted a `ValError`/`ValFatalError` as a regular value and didn't forward the error. 
Fix the issue by adding the validation of the arguments before invoking the function. 
closes https://github.com/camunda/camunda/issues/26054
=> fix: A unary-test expression with ? returns true/false

src/main/scala/org/camunda/feel/FeelEngine.scala
Backport of #960 to `1.17`.
relates to camunda/camunda#26395
original author: @npepinpe
=> [Backport 1.17] refactor: lower log level to debug

src/main/scala/org/camunda/feel/FeelEngine.scala
Backport of #960 to `1.19`.
relates to camunda/camunda#26395
original author: @npepinpe
=> [Backport 1.19] refactor: lower log level to debug

src/main/scala/org/camunda/feel/FeelEngine.scala
Backport of #960 to `1.18`.
relates to camunda/camunda#26395
original author: @npepinpe
=> [Backport 1.18] refactor: lower log level to debug

src/main/scala/org/camunda/feel/impl/builtin/BuiltinFunction.scala, src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
Backport of #959 to `1.17`.
relates to camunda/camunda#26054
=> [Backport 1.17] fix: A unary-test expression with ? returns true/false

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
Fix a regression for unary-test expressions. If the expression evaluates to `false` and the input value is of a different type, the unary-test should return `false` instead of `null`.
closes https://github.com/camunda/camunda/issues/27004
=> fix: A unary-test expression returns null instead of false

src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
List functions should return `null` if the position is zero. A position must be positive or negative but not zero.
Effected functions:
- `remove()`
- `sublist()`
- `insert before()`
closes #957
=> fix: List functions handle invalid zero position 

src/main/scala/org/camunda/feel/impl/builtin/ListBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinListFunctionsTest.scala
Backport of #970 to `1.19`.
relates to #957
=> [Backport 1.19] fix: List functions handle invalid zero position 

src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala, src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala
Backport of #969 to `1.17`.
relates to camunda/camunda#27004
=> [Backport 1.17] fix: A unary-test expression returns null instead of false

src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/test/scala/org/camunda/feel/api/StringRepresentationTypeTest.scala
* Add test cases to verify that a duration returns a normalized value
* Fix the string format of a years-months-duration to return a normalized string format. 
related to #953
=> fix: Return normalized years-months-duration 

src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/test/scala/org/camunda/feel/api/StringRepresentationTypeTest.scala
Backport of #971 to `1.19`.
relates to #953
=> [Backport 1.19] fix: Return normalized years-months-duration 

src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/test/scala/org/camunda/feel/api/StringRepresentationTypeTest.scala
Backport of #971 to `1.18`.
relates to #953
=> [Backport 1.18] fix: Return normalized years-months-duration 

src/main/scala/org/camunda/feel/syntaxtree/Val.scala, src/test/scala/org/camunda/feel/api/StringRepresentationTypeTest.scala
Backport of #971 to `1.17`.
relates to #953
=> [Backport 1.17] fix: Return normalized years-months-duration 

src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
Previously, the builtin context#put function was expecting to
receive a fully mapped context (including all nested variables).
But this can not always be guaranteed as some VariableProviders
can only resolve variables lazily, because of performance/memory
concerns.
For example, in camunda engine we don't want to decode all possible
variables of a process/element-scope at once as most of them might
not be needed by the expression at all.
Closes https://github.com/camunda/camunda/issues/29752
=> eppdot-fix-lazy-value-mapper

src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
Backport of #993 to `1.17`.
relates to camunda/camunda#29752
original author: @eppdot
=> [Backport 1.17] eppdot-fix-lazy-value-mapper

src/main/scala/org/camunda/feel/impl/builtin/ContextBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala
Backport of #993 to `1.18`.
relates to camunda/camunda#29752
original author: @eppdot
=> [Backport 1.18] eppdot-fix-lazy-value-mapper

pom.xml
related to [AP7 #5072](https://github.com/camunda/camunda-bpm-platform/issues/5072#issue-2971765725)
This is to address the issue reported in https://github.com/camunda/camunda-bpm-platform/issues/5072#issue-2971765725. We have also had a support ticket relating to this issue (to be linked in the AP7 ticket)
The fasterxml dependency was not added to the relocation config for the maven-shade-plugin, leading to conflicts.
Before changes from this PR:
```
jar tvf feel-engine-1.20.0-SNAPSHOT-scala-shaded.jar  
[...]
0 Fri Feb 01 08:00:00 ICT 1980 com/fasterxml/uuid/
1096 Fri Feb 01 08:00:00 ICT 1980 com/fasterxml/uuid/EgressInterfaceFinder$1.class
1246 Fri Feb 01 08:00:00 ICT 1980 com/fasterxml/uuid/EgressInterfaceFinder$2.class
1258 Fri Feb 01 08:00:00 ICT 1980 …
```
=> chore(fasterxml): add relocation for fasterxml shading

pom.xml
Backport https://github.com/camunda/feel-scala/pull/1012 to 1.18.Backport https://github.com/camunda/feel-scala/pull/1012 to 1.19.
=> chore: switch to Sonatype Central Portal deployment (1.19)

pom.xml
Backport https://github.com/camunda/feel-scala/pull/1012 to 1.18.
=> chore: switch to Sonatype Central Portal deployment (1.18)

pom.xml
Backport https://github.com/camunda/feel-scala/pull/1012 to 1.17.
=> chore: switch to Sonatype Central Portal deployment (1.17)

pom.xml, src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala, src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala
This PR adds a new `from json(string): Any` built-in conversion function, allowing users to convert stringified-JSON results (very common with agentic orchestration) into objects, such as contexts, lists, strings, etc. This simplifies extracting, transforming, etc., parts from such results.
The tests were largely taken [from this comment](https://github.com/camunda/feel-scala/issues/602#issuecomment-1591197695), major thanks for this :pray: 
One small issue, Jackson requires an additional compiler file, `Ytasty-reader`. I'm a complete Scala noob, so while I could add it and make progress, I cannot speak for its impact and if that's something we want to move forward with: does it mean downstream users also need to add this flag? If so, do we want that?
closes #825
=> Add `from json(string): Any` conversion function
